declare const require: {
    context(
      directory: string,
      useSubdirectories?: boolean,
      regExp?: RegExp,
    ): __WebpackModuleApi.RequireContext;
  };

export type ReactAnimalNames = 
  | 'alligator'
  | 'anteater'
  | 'armadillo'
  | 'auroch'
  | 'axolotl'
  | 'badger'
  | 'bat'
  | 'beaver'
  | 'buffalo'
  | 'camel'
  | 'capybara'
  | 'chameleon'
  | 'cheetah'
  | 'chinchilla'
  | 'chipmunk'
  | 'chupacabra'
  | 'cormorant'
  | 'coyote'
  | 'crow'
  | 'dingo'
  | 'dinosaur'
  | 'dolphin'
  | 'duck'
  | 'elephant'
  | 'ferret'
  | 'fox'
  | 'frog'
  | 'giraffe'
  | 'gopher'
  | 'grizzly'
  | 'hedgehog'
  | 'hippo'
  | 'hyena'
  | 'ibex'
  | 'ifrit'
  | 'iguana'
  | 'jackal'
  | 'kangaroo'
  | 'koala'
  | 'kraken'
  | 'lemur'
  | 'leopard'
  | 'liger'
  | 'llama'
  | 'manatee'
  | 'mink'
  | 'monkey'
  | 'moose'
  | 'narwhal'
  | 'orangutan'
  | 'otter'
  | 'panda'
  | 'penguin'
  | 'platypus'
  | 'pumpkin'
  | 'python'
  | 'quagga'
  | 'rabbit'
  | 'raccoon'
  | 'rhino'
  | 'sheep'
  | 'shrew'
  | 'skunk'
  | 'squirrel'
  | 'tiger'
  | 'turtle'
  | 'walrus'
  | 'wolf'
  | 'wolverine'
  | 'wombat';

const animalImages = require.context('./images', false, /\.png$/);

export const animalImageMap: Record<ReactAnimalNames, string> = {
  alligator: animalImages('./alligator.png').default.default,
  anteater: animalImages('./anteater.png').default,
  armadillo: animalImages('./armadillo.png').default,
  auroch: animalImages('./auroch.png').default,
  axolotl: animalImages('./axolotl.png').default,
  badger: animalImages('./badger.png').default,
  bat: animalImages('./bat.png').default,
  beaver: animalImages('./beaver.png').default,
  buffalo: animalImages('./buffalo.png').default,
  camel: animalImages('./camel.png').default,
  capybara: animalImages('./capybara.png').default,
  chameleon: animalImages('./chameleon.png').default,
  cheetah: animalImages('./cheetah.png').default,
  chinchilla: animalImages('./chinchilla.png').default,
  chipmunk: animalImages('./chipmunk.png').default,
  chupacabra: animalImages('./chupacabra.png').default,
  cormorant: animalImages('./cormorant.png').default,
  coyote: animalImages('./coyote.png').default,
  crow: animalImages('./crow.png').default,
  dingo: animalImages('./dingo.png').default,
  dinosaur: animalImages('./dinosaur.png').default,
  dolphin: animalImages('./dolphin.png').default,
  duck: animalImages('./duck.png').default,
  elephant: animalImages('./elephant.png').default,
  ferret: animalImages('./ferret.png').default,
  fox: animalImages('./fox.png').default,
  frog: animalImages('./frog.png').default,
  giraffe: animalImages('./giraffe.png').default,
  gopher: animalImages('./gopher.png').default,
  grizzly: animalImages('./grizzly.png').default,
  hedgehog: animalImages('./hedgehog.png').default,
  hippo: animalImages('./hippo.png').default,
  hyena: animalImages('./hyena.png').default,
  ibex: animalImages('./ibex.png').default,
  ifrit: animalImages('./ifrit.png').default,
  iguana: animalImages('./iguana.png').default,
  jackal: animalImages('./jackal.png').default,
  kangaroo: animalImages('./kangaroo.png').default,
  koala: animalImages('./koala.png').default,
  kraken: animalImages('./kraken.png').default,
  lemur: animalImages('./lemur.png').default,
  leopard: animalImages('./leopard.png').default,
  liger: animalImages('./liger.png').default,
  llama: animalImages('./llama.png').default,
  manatee: animalImages('./manatee.png').default,
  mink: animalImages('./mink.png').default,
  monkey: animalImages('./monkey.png').default,
  moose: animalImages('./moose.png').default,
  narwhal: animalImages('./narwhal.png').default,
  orangutan: animalImages('./orangutan.png').default,
  otter: animalImages('./otter.png').default,
  panda: animalImages('./panda.png').default,
  penguin: animalImages('./penguin.png').default,
  platypus: animalImages('./platypus.png').default,
  pumpkin: animalImages('./pumpkin.png').default,
  python: animalImages('./python.png').default,
  quagga: animalImages('./quagga.png').default,
  rabbit: animalImages('./rabbit.png').default,
  raccoon: animalImages('./raccoon.png').default,
  rhino: animalImages('./rhino.png').default,
  sheep: animalImages('./sheep.png').default,
  shrew: animalImages('./shrew.png').default,
  skunk: animalImages('./skunk.png').default,
  squirrel: animalImages('./squirrel.png').default,
  tiger: animalImages('./tiger.png').default,
  turtle: animalImages('./turtle.png').default,
  walrus: animalImages('./walrus.png').default,
  wolf: animalImages('./wolf.png').default,
  wolverine: animalImages('./wolverine.png').default,
  wombat: animalImages('./wombat.png').default,
};

export const animalNames = Object.keys(animalImageMap) as ReactAnimalNames[];
